"""
analytics_agent.py – Scheduled Data Analytics Agent.
Reads master Google Sheet, computes KPIs, and emails an HTML report to staff.
Can be run standalone or triggered by schedule in main.py.
"""
import logging
from datetime import datetime
import gspread
from google.oauth2.service_account import Credentials
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Content
from config import (
    GOOGLE_SHEET_ID, SHEET_NAME, GOOGLE_SERVICE_ACCOUNT_JSON,
    SENDGRID_API_KEY, ANALYTICS_FROM_EMAIL, ANALYTICS_TO_EMAILS,
    DRY_RUN,
)

logger = logging.getLogger(__name__)

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets.readonly",
    "https://www.googleapis.com/auth/drive.readonly",
]


def _get_records() -> list[dict]:
    creds = Credentials.from_service_account_file(GOOGLE_SERVICE_ACCOUNT_JSON, scopes=SCOPES)
    client = gspread.authorize(creds)
    ws = client.open_by_key(GOOGLE_SHEET_ID).worksheet(SHEET_NAME)
    return ws.get_all_records()


def _compute_metrics(records: list[dict]) -> dict:
    total = len(records)
    sent = sum(1 for r in records if str(r.get("delivery_status", "")).lower() == "sent")
    failed = sum(1 for r in records if str(r.get("delivery_status", "")).lower() == "failed")
    completed = sum(1 for r in records if str(r.get("status", "")).lower() == "completed")
    errors = sum(1 for r in records if str(r.get("status", "")).lower() == "error")

    follow_ups = [r for r in records if str(r.get("action_type", "")).lower() == "follow_up"]
    upsells    = [r for r in records if str(r.get("action_type", "")).lower() == "upsell"]
    feedbacks  = [r for r in records if str(r.get("action_type", "")).lower() == "feedback"]

    upsell_conversions = sum(
        1 for r in upsells if str(r.get("delivery_status", "")).lower() == "sent"
    )

    delivery_rate = round(sent / total * 100, 1) if total else 0

    return {
        "total_records":       total,
        "messages_sent":       sent,
        "messages_failed":     failed,
        "rows_completed":      completed,
        "rows_error":          errors,
        "delivery_rate_pct":   delivery_rate,
        "follow_up_count":     len(follow_ups),
        "upsell_count":        len(upsells),
        "upsell_conversions":  upsell_conversions,
        "feedback_count":      len(feedbacks),
        "follow_up_completion": round(
            sum(1 for r in follow_ups if str(r.get("status","")).lower() == "completed")
            / max(len(follow_ups), 1) * 100, 1
        ),
        "report_generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }


def _build_html_report(m: dict) -> str:
    return f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; color: #333; max-width: 650px; margin: auto; }}
  h1 {{ background: #1a73e8; color: white; padding: 16px; border-radius: 6px; }}
  h2 {{ color: #1a73e8; border-bottom: 2px solid #e0e0e0; padding-bottom: 6px; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 24px; }}
  th {{ background: #f1f3f4; text-align: left; padding: 10px; }}
  td {{ padding: 10px; border-bottom: 1px solid #e0e0e0; }}
  .kpi {{ font-size: 2em; font-weight: bold; color: #1a73e8; }}
  .green {{ color: #34a853; }} .red {{ color: #ea4335; }}
  footer {{ font-size: 12px; color: #888; margin-top: 32px; }}
</style>
</head>
<body>
<h1>🏥 Patient Engagement Agent – Analytics Report</h1>
<p>Generated: <strong>{m['report_generated_at']}</strong></p>

<h2>📊 Overview</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Total Patient Records</td><td><span class="kpi">{m['total_records']}</span></td></tr>
  <tr><td>Messages Sent</td><td class="green"><strong>{m['messages_sent']}</strong></td></tr>
  <tr><td>Messages Failed</td><td class="red"><strong>{m['messages_failed']}</strong></td></tr>
  <tr><td>Delivery Rate</td><td><strong>{m['delivery_rate_pct']}%</strong></td></tr>
  <tr><td>Rows Completed</td><td>{m['rows_completed']}</td></tr>
  <tr><td>Rows Error</td><td class="red">{m['rows_error']}</td></tr>
</table>

<h2>📋 Branch Breakdown</h2>
<table>
  <tr><th>Branch</th><th>Total Rows</th><th>Notes</th></tr>
  <tr><td>Follow-Up</td><td>{m['follow_up_count']}</td>
      <td>Completion: {m['follow_up_completion']}%</td></tr>
  <tr><td>Upsell</td><td>{m['upsell_count']}</td>
      <td>Conversions (sent): {m['upsell_conversions']}</td></tr>
  <tr><td>Feedback</td><td>{m['feedback_count']}</td><td>–</td></tr>
</table>

<h2>💰 Revenue Impact</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Upsell Messages Sent</td><td>{m['upsell_conversions']}</td></tr>
  <tr><td>Est. Conversion Opportunities</td><td>{m['upsell_conversions']} patients reached</td></tr>
</table>

<footer>
  This report was automatically generated by the Healthcare AI Patient Engagement Agent.<br>
  Do not reply to this email. Data source: Google Sheet ID {GOOGLE_SHEET_ID}
</footer>
</body>
</html>
"""


def _send_email(html_body: str, subject: str) -> bool:
    if DRY_RUN:
        logger.info("[DRY RUN] Would email analytics report to: %s", ANALYTICS_TO_EMAILS)
        return True
    try:
        sg = SendGridAPIClient(SENDGRID_API_KEY)
        mail = Mail(
            from_email=ANALYTICS_FROM_EMAIL,
            to_emails=ANALYTICS_TO_EMAILS,
            subject=subject,
        )
        mail.content = [Content("text/html", html_body)]
        resp = sg.send(mail)
        logger.info("Analytics email sent. Status: %s", resp.status_code)
        return resp.status_code in (200, 202)
    except Exception as e:
        logger.error("Failed to send analytics email: %s", e)
        return False


def run_analytics():
    """Entry point – compute metrics and email report."""
    logger.info("=== Analytics Agent: starting ===")
    records = _get_records()
    metrics = _compute_metrics(records)
    html = _build_html_report(metrics)
    subject = f"Patient Engagement Report – {metrics['report_generated_at'][:10]}"
    ok = _send_email(html, subject)
    if ok:
        logger.info("Analytics report delivered.")
    else:
        logger.error("Analytics report delivery failed.")
    return metrics


if __name__ == "__main__":
    import logging as _log
    _log.basicConfig(level="INFO", format="%(levelname)s %(message)s")
    run_analytics()
